import { db } from "./db.js";
 
// Restaurant cover images — used on the restaurant list/detail hero.
// Each URL is a specific Unsplash food photo matching the restaurant's cuisine.
const RESTAURANT_IMG = {
  biryani: "https://images.unsplash.com/photo-1563379091339-03246963d96c?w=800&q=80",
  southIndian: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&q=80",
  pizza: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
  burger: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
  chinese: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&q=80",
  dessert: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&q=80",
  northIndian: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80",
  cafe: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
  pasta: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
  streetFood: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800&q=80",
};
 
const restaurants = [
  {
    id: "r1",
    name: "Nizam's Biryani House",
    image_id: RESTAURANT_IMG.biryani,
    cuisines: ["Biryani", "Hyderabadi", "Mughlai"],
    area: "Madhapur",
    city: "Hyderabad",
    avg_rating: 4.4,
    rating_count: "2.3K+",
    delivery_min: 25,
    delivery_max: 35,
    cost_for_two: 400,
    is_veg_only: 0,
    is_promoted: 1,
    discount_text: "50% OFF up to ₹100",
  },
  {
    id: "r2",
    name: "Andhra Spice Junction",
    image_id: RESTAURANT_IMG.southIndian,
    cuisines: ["South Indian", "Andhra", "Tiffins"],
    area: "Vizianagaram",
    city: "Vizianagaram",
    avg_rating: 4.6,
    rating_count: "1.8K+",
    delivery_min: 20,
    delivery_max: 30,
    cost_for_two: 250,
    is_veg_only: 1,
    is_promoted: 0,
    discount_text: null,
  },
  {
    id: "r3",
    name: "Pizza Forge",
    image_id: RESTAURANT_IMG.pizza,
    cuisines: ["Pizza", "Italian", "Fast Food"],
    area: "Gachibowli",
    city: "Hyderabad",
    avg_rating: 4.1,
    rating_count: "980+",
    delivery_min: 30,
    delivery_max: 40,
    cost_for_two: 500,
    is_veg_only: 0,
    is_promoted: 1,
    discount_text: "Flat ₹125 OFF",
  },
  {
    id: "r4",
    name: "The Burger Lab",
    image_id: RESTAURANT_IMG.burger,
    cuisines: ["Burgers", "American", "Fast Food"],
    area: "Banjara Hills",
    city: "Hyderabad",
    avg_rating: 4.3,
    rating_count: "1.2K+",
    delivery_min: 20,
    delivery_max: 30,
    cost_for_two: 350,
    is_veg_only: 0,
    is_promoted: 0,
    discount_text: null,
  },
  {
    id: "r5",
    name: "Golden Dragon Wok",
    image_id: RESTAURANT_IMG.chinese,
    cuisines: ["Chinese", "Asian", "Momos"],
    area: "Kondapur",
    city: "Hyderabad",
    avg_rating: 4.0,
    rating_count: "760+",
    delivery_min: 25,
    delivery_max: 35,
    cost_for_two: 400,
    is_veg_only: 0,
    is_promoted: 0,
    discount_text: null,
  },
  {
    id: "r6",
    name: "Sweet Ending Desserts",
    image_id: RESTAURANT_IMG.dessert,
    cuisines: ["Desserts", "Bakery", "Ice Cream"],
    area: "Jubilee Hills",
    city: "Hyderabad",
    avg_rating: 4.7,
    rating_count: "3.1K+",
    delivery_min: 15,
    delivery_max: 25,
    cost_for_two: 200,
    is_veg_only: 1,
    is_promoted: 1,
    discount_text: "20% OFF",
  },
  {
    id: "r7",
    name: "Punjabi Tadka",
    image_id: RESTAURANT_IMG.northIndian,
    cuisines: ["North Indian", "Punjabi", "Tandoor"],
    area: "Ameerpet",
    city: "Hyderabad",
    avg_rating: 4.2,
    rating_count: "1.5K+",
    delivery_min: 30,
    delivery_max: 40,
    cost_for_two: 450,
    is_veg_only: 0,
    is_promoted: 0,
    discount_text: null,
  },
  {
    id: "r8",
    name: "The Daily Grind Café",
    image_id: RESTAURANT_IMG.cafe,
    cuisines: ["Café", "Continental", "Beverages"],
    area: "Himayatnagar",
    city: "Hyderabad",
    avg_rating: 4.5,
    rating_count: "2.0K+",
    delivery_min: 20,
    delivery_max: 30,
    cost_for_two: 300,
    is_veg_only: 0,
    is_promoted: 0,
    discount_text: null,
  },
  {
    id: "r9",
    name: "Roma Pasta Bar",
    image_id: RESTAURANT_IMG.pasta,
    cuisines: ["Italian", "Pasta", "Continental"],
    area: "Kukatpally",
    city: "Hyderabad",
    avg_rating: 3.9,
    rating_count: "540+",
    delivery_min: 35,
    delivery_max: 45,
    cost_for_two: 550,
    is_veg_only: 0,
    is_promoted: 0,
    discount_text: null,
  },
  {
    id: "r10",
    name: "Chaat Street Corner",
    image_id: RESTAURANT_IMG.streetFood,
    cuisines: ["Street Food", "Chaat", "North Indian"],
    area: "Nuzvid",
    city: "Vizianagaram",
    avg_rating: 4.4,
    rating_count: "1.1K+",
    delivery_min: 15,
    delivery_max: 25,
    cost_for_two: 150,
    is_veg_only: 1,
    is_promoted: 0,
    discount_text: null,
  },
];
 
// Every menu item carries its OWN image URL that matches the dish.
// (Previously, item images were picked round-robin from a 10-image pool,
// so most items showed a completely unrelated photo. Fixed now.)
const menuByRestaurant = {
  r1: [
    { category: "Biryani", name: "Hyderabadi Chicken Dum Biryani", description: "Slow-cooked basmati rice layered with marinated chicken, saffron and fried onions.", price: 280, isVeg: false, isBestseller: false,
      image: "https://images.unsplash.com/photo-1563379091339-03246963d96c?w=600&q=80" },
    { category: "Biryani", name: "Mutton Biryani", description: "Tender mutton pieces dum-cooked with long-grain basmati and whole spices.", price: 340, isVeg: false, isBestseller: true,
      image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=600&q=80" },
    { category: "Biryani", name: "Veg Dum Biryani", description: "Mixed vegetables and paneer layered with fragrant basmati rice.", price: 220, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&q=80" },
    { category: "Starters", name: "Chicken 65", description: "Crispy deep-fried chicken tossed in curry leaves and red chilli.", price: 190, isVeg: false, isBestseller: false,
      image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&q=80" },
    { category: "Starters", name: "Mirchi Ka Salan", description: "Tangy peanut and sesame gravy with green chillies, a classic biryani side.", price: 90, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&q=80" },
    { category: "Beverages", name: "Sweet Lassi", description: "Chilled, thick yogurt drink sweetened lightly.", price: 60, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1626200925683-90ba1c02c9e4?w=600&q=80" },
  ],
  r2: [
    { category: "Tiffins", name: "Masala Dosa", description: "Crisp rice-lentil crepe filled with spiced potato masala, served with sambar and chutney.", price: 90, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&q=80" },
    { category: "Tiffins", name: "Idli Sambar (4 pcs)", description: "Steamed rice cakes served with sambar and coconut chutney.", price: 70, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&q=80" },
    { category: "Tiffins", name: "Pesarattu", description: "Green gram dosa, an Andhra breakfast staple, served with ginger chutney.", price: 85, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&q=80" },
    { category: "Curries", name: "Gongura Mutton", description: "Tangy sorrel-leaf curry cooked with tender mutton, an Andhra specialty.", price: 260, isVeg: false, isBestseller: true,
      image: "https://images.unsplash.com/photo-1545247181-516773cae754?w=600&q=80" },
    { category: "Curries", name: "Pappu Charu", description: "Traditional Andhra lentil soup tempered with garlic and red chillies.", price: 80, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80" },
    { category: "Rice", name: "Curd Rice", description: "Comforting rice tempered with mustard seeds and curry leaves, mixed with yogurt.", price: 70, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&q=80" },
  ],
  r3: [
    { category: "Pizza", name: "Margherita", description: "Classic tomato sauce, fresh mozzarella and basil on a hand-tossed base.", price: 249, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=600&q=80" },
    { category: "Pizza", name: "Peri-Peri Chicken", description: "Spicy peri-peri marinated chicken, onions and bell peppers.", price: 349, isVeg: false, isBestseller: true,
      image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&q=80" },
    { category: "Pizza", name: "Farmhouse", description: "Onion, capsicum, tomato, mushroom and sweet corn.", price: 299, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80" },
    { category: "Sides", name: "Garlic Bread", description: "Toasted baguette with garlic butter and oregano.", price: 129, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=600&q=80" },
    { category: "Sides", name: "Cheesy Fries", description: "Crinkle-cut fries loaded with molten cheese sauce.", price: 149, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&q=80" },
  ],
  r4: [
    { category: "Burgers", name: "Classic Smash Burger", description: "Double smashed chicken patty, cheddar, house sauce.", price: 199, isVeg: false, isBestseller: true,
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80" },
    { category: "Burgers", name: "Crispy Veg Burger", description: "Crumb-fried vegetable patty with lettuce and mayo.", price: 149, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&q=80" },
    { category: "Burgers", name: "BBQ Bacon Burger", description: "Grilled chicken patty, smoky BBQ sauce and crispy onions.", price: 229, isVeg: false, isBestseller: false,
      image: "https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=600&q=80" },
    { category: "Sides", name: "Loaded Nachos", description: "Tortilla chips topped with cheese, jalapenos and salsa.", price: 169, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=600&q=80" },
    { category: "Beverages", name: "Classic Milkshake", description: "Thick vanilla or chocolate milkshake.", price: 120, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1568901839119-05e34e3ad8a5?w=600&q=80" },
  ],
  r5: [
    { category: "Momos", name: "Steamed Chicken Momos (8 pcs)", description: "Juicy chicken dumplings served with spicy chutney.", price: 160, isVeg: false, isBestseller: true,
      image: "https://images.unsplash.com/photo-1626776877216-b2b0b30dcd58?w=600&q=80" },
    { category: "Momos", name: "Veg Momos (8 pcs)", description: "Cabbage and carrot dumplings, steamed and served with chilli oil.", price: 130, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&q=80" },
    { category: "Noodles", name: "Hakka Noodles", description: "Wok-tossed noodles with julienned vegetables and soy.", price: 180, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80" },
    { category: "Rice", name: "Chicken Fried Rice", description: "Classic wok-fried rice with egg, chicken and spring onion.", price: 200, isVeg: false, isBestseller: false,
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80" },
    { category: "Soups", name: "Hot & Sour Soup", description: "Spicy, tangy vegetable broth with a hint of vinegar.", price: 90, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80" },
  ],
  r6: [
    { category: "Cakes", name: "Belgian Chocolate Truffle (500g)", description: "Rich layered chocolate sponge with dark chocolate ganache.", price: 450, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=600&q=80" },
    { category: "Ice Cream", name: "Gulab Jamun Sundae", description: "Warm gulab jamun over vanilla ice cream with rabri drizzle.", price: 150, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=600&q=80" },
    { category: "Pastries", name: "Red Velvet Pastry", description: "Classic red velvet sponge with cream cheese frosting.", price: 90, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1586788680434-30d324b2d46f?w=600&q=80" },
    { category: "Beverages", name: "Cold Coffee with Ice Cream", description: "Chilled coffee blended with vanilla ice cream.", price: 130, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600&q=80" },
  ],
  r7: [
    { category: "Tandoor", name: "Butter Chicken", description: "Char-grilled chicken simmered in a rich tomato-butter gravy.", price: 320, isVeg: false, isBestseller: true,
      image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&q=80" },
    { category: "Tandoor", name: "Paneer Tikka", description: "Char-grilled cottage cheese marinated in yogurt and spices.", price: 260, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&q=80" },
    { category: "Breads", name: "Butter Naan", description: "Soft leavened bread brushed with butter, baked in the tandoor.", price: 45, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?w=600&q=80" },
    { category: "Curries", name: "Dal Makhani", description: "Slow-cooked black lentils finished with cream and butter.", price: 210, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80" },
    { category: "Rice", name: "Jeera Rice", description: "Basmati rice tempered with cumin seeds and ghee.", price: 150, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&q=80" },
  ],
  r8: [
    { category: "Beverages", name: "Cappuccino", description: "Espresso with steamed milk foam.", price: 140, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80" },
    { category: "Beverages", name: "Cold Brew", description: "Slow-steeped, smooth cold coffee concentrate over ice.", price: 160, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&q=80" },
    { category: "Snacks", name: "Club Sandwich", description: "Triple-layer sandwich with grilled chicken, egg and veggies.", price: 210, isVeg: false, isBestseller: true,
      image: "https://images.unsplash.com/photo-1567234669003-dce7a7a88821?w=600&q=80" },
    { category: "Snacks", name: "Avocado Toast", description: "Sourdough toast topped with mashed avocado, chilli flakes and feta.", price: 220, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=600&q=80" },
    { category: "Desserts", name: "New York Cheesecake", description: "Classic baked cheesecake with a buttery biscuit base.", price: 180, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&q=80" },
  ],
  r9: [
    { category: "Pasta", name: "Spaghetti Aglio e Olio", description: "Garlic and olive oil tossed spaghetti with chilli flakes and parsley.", price: 250, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80" },
    { category: "Pasta", name: "Chicken Alfredo Penne", description: "Creamy Alfredo sauce with grilled chicken and penne pasta.", price: 320, isVeg: false, isBestseller: true,
      image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=600&q=80" },
    { category: "Risotto", name: "Mushroom Risotto", description: "Creamy Arborio rice slow-cooked with wild mushrooms and parmesan.", price: 340, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1633964913849-96bb09cd45de?w=600&q=80" },
    { category: "Sides", name: "Bruschetta", description: "Toasted bread topped with tomato, basil and olive oil.", price: 160, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=600&q=80" },
  ],
  r10: [
    { category: "Chaat", name: "Pani Puri (8 pcs)", description: "Crisp hollow puris filled with tangy spiced water and potato.", price: 50, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&q=80" },
    { category: "Chaat", name: "Bhel Puri", description: "Puffed rice tossed with tangy tamarind chutney, onions and sev.", price: 60, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&q=80" },
    { category: "Chaat", name: "Samosa Chaat", description: "Crushed samosas topped with chickpea curry, yogurt and chutneys.", price: 80, isVeg: true, isBestseller: true,
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&q=80" },
    { category: "Beverages", name: "Masala Chaas", description: "Spiced buttermilk with roasted cumin and mint.", price: 40, isVeg: true, isBestseller: false,
      image: "https://images.unsplash.com/photo-1626200925683-90ba1c02c9e4?w=600&q=80" },
  ],
};
 
const insertRestaurant = db.prepare(`
  INSERT OR REPLACE INTO restaurants
    (id, name, image_id, cuisines, area, city, avg_rating, rating_count,
     delivery_min, delivery_max, cost_for_two, is_veg_only, is_promoted, discount_text)
  VALUES (@id, @name, @image_id, @cuisines, @area, @city, @avg_rating, @rating_count,
     @delivery_min, @delivery_max, @cost_for_two, @is_veg_only, @is_promoted, @discount_text)
`);
 
const insertMenuItem = db.prepare(`
  INSERT OR REPLACE INTO menu_items
    (id, restaurant_id, category, name, description, price, image_id, is_veg, is_bestseller, rating)
  VALUES (@id, @restaurant_id, @category, @name, @description, @price, @image_id, @is_veg, @is_bestseller, @rating)
`);
 
const seed = db.transaction(() => {
  db.exec("DELETE FROM order_items; DELETE FROM orders; DELETE FROM menu_items; DELETE FROM restaurants;");
 
  for (const r of restaurants) {
    insertRestaurant.run({ ...r, cuisines: JSON.stringify(r.cuisines) });
  }
 
  for (const [restaurantId, items] of Object.entries(menuByRestaurant)) {
    items.forEach((item, idx) => {
      insertMenuItem.run({
        id: `${restaurantId}-item-${idx}`,
        restaurant_id: restaurantId,
        category: item.category,
        name: item.name,
        description: item.description,
        price: item.price,
        image_id: item.image, // now uses per-item image, not a round-robin pick
        is_veg: item.isVeg ? 1 : 0,
        is_bestseller: item.isBestseller ? 1 : 0,
        rating: +(3.5 + Math.random() * 1.4).toFixed(1),
      });
    });
  }
});
 
seed();
console.log(`Seeded ${restaurants.length} restaurants and ${Object.values(menuByRestaurant).flat().length} menu items.`);